from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    ProductViewSet,
    StoreViewSet,
    cancel_order,
    cancel_wholesale_order,
    complete_order,
    complete_wholesale_order,
    create_listing_request,
    create_wholesale_order,
    current_user,
    delete_notification,
    delete_order,
    delete_wholesale_order,
    health_check,
    homepage_data,
    login_user,
    logout_user,
    mark_all_notifications_read,
    mark_notification_read,
    my_listings,
    order_detail,
    orders,
    notifications,
    product_deals,
    register_user,
    create_stock_listing,
    stock_items,
    update_account_settings,
    upload_stock_items,
    wholesale_listing_detail,
    wholesale_listings,
    wholesale_order_detail,
)


router = DefaultRouter()
router.register("stores", StoreViewSet, basename="store")
router.register("products", ProductViewSet, basename="product")

urlpatterns = [
    path("", include(router.urls)),
    path("health/", health_check, name="health-check"),
    path("homepage/", homepage_data, name="homepage-data"),
    path("products/<int:product_id>/deals/", product_deals, name="product-deals"),
    path("products/<int:product_id>/request/", create_listing_request, name="create-listing-request"),
    path("orders/", orders, name="orders"),
    path("orders/<int:order_id>/", order_detail, name="order-detail"),
    path("orders/<int:order_id>/complete/", complete_order, name="complete-order"),
    path("orders/<int:order_id>/cancel/", cancel_order, name="cancel-order"),
    path("orders/<int:order_id>/delete/", delete_order, name="delete-order"),
    path("wholesale/listings/", wholesale_listings, name="wholesale-listings"),
    path("wholesale/listings/<int:listing_id>/", wholesale_listing_detail, name="wholesale-listing-detail"),
    path("wholesale/listings/<int:listing_id>/order/", create_wholesale_order, name="create-wholesale-order"),
    path("wholesale/orders/<int:order_id>/", wholesale_order_detail, name="wholesale-order-detail"),
    path("wholesale/orders/<int:order_id>/complete/", complete_wholesale_order, name="complete-wholesale-order"),
    path("wholesale/orders/<int:order_id>/cancel/", cancel_wholesale_order, name="cancel-wholesale-order"),
    path("wholesale/orders/<int:order_id>/delete/", delete_wholesale_order, name="delete-wholesale-order"),
    path("notifications/", notifications, name="notifications"),
    path("notifications/read-all/", mark_all_notifications_read, name="mark-all-notifications-read"),
    path("notifications/<int:notification_id>/read/", mark_notification_read, name="mark-notification-read"),
    path("notifications/<int:notification_id>/", delete_notification, name="delete-notification"),
    path("my-listings/", my_listings, name="my-listings"),
    path("stock/", stock_items, name="stock-items"),
    path("stock/upload/", upload_stock_items, name="upload-stock-items"),
    path("stock/<int:stock_item_id>/list/", create_stock_listing, name="create-stock-listing"),
    path("auth/register/", register_user, name="register-user"),
    path("auth/login/", login_user, name="login-user"),
    path("auth/logout/", logout_user, name="logout-user"),
    path("auth/me/", current_user, name="current-user"),
    path("auth/settings/", update_account_settings, name="update-account-settings"),
]
