# Generated by Django 5.2.13 on 2026-04-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_listingrequest_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='building_details',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
