# Generated by Django 5.2.13 on 2026-04-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_accountprofile_building_details_accountprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingrequest',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='hidden_for_requester',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='hidden_for_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
