# Generated by Django 5.2.13 on 2026-04-23 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_listingrequest_canceled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_units', models.PositiveIntegerField(default=0)),
                ('min_order_quantity', models.PositiveIntegerField(default=5)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('distance_miles', models.DecimalField(decimal_places=1, default=1.0, max_digits=5)),
                ('stock_status', models.CharField(choices=[('available', 'Available'), ('low', 'Low Stock'), ('critical', 'Critical Stock')], default='available', max_length=20)),
                ('demand_level', models.CharField(choices=[('low', 'Low Demand'), ('medium', 'Medium Demand'), ('high', 'High Demand')], default='medium', max_length=20)),
                ('is_trending', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_listings', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_listings', to='catalog.store')),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('stock_request', 'Stock Request'), ('offer', 'Offer')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_for_requester', models.BooleanField(default=False)),
                ('hidden_for_seller', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='catalog.wholesalelisting')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_wholesale_orders', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_wholesale_orders', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_orders', to='catalog.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
