# Generated by Django 5.2.13 on 2026-04-23 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_wholesalelisting_wholesaleorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('product_name', models.CharField(max_length=180)),
                ('category', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('suggested_retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('suggested_wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_order_quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('new', 'New'), ('open_box', 'Open box'), ('used', 'Used'), ('refurbished', 'Refurbished')], default='new', max_length=20)),
                ('depot_location', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('source_file', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalog.store')),
            ],
            options={
                'ordering': ['product_name', 'sku'],
            },
        ),
    ]
